import { create } from 'zustand';
export const useStore = create((set, get) => ({
  currentView: 'dashboard', selectedHabitId: null,
  setView: (v, id=null) => set({ currentView: v, selectedHabitId: id }),
  colorMode: 'light', setColorMode: (m) => set({ colorMode: m }),
  isAuthenticated: false, passwordEnabled: false,
  setAuthenticated: (v) => set({ isAuthenticated: v }), setPasswordEnabled: (v) => set({ passwordEnabled: v }),
  tutorialDone: false, setTutorialDone: (v) => set({ tutorialDone: v }),
  habits: [], completions: [], journalEntries: [], dayNotes: [], focusSessions: [], vacationPeriods: [],
  tasks: [], notes: [], homework: [], subjects: [],
  setHabits: (h) => set({ habits: h }), setCompletions: (c) => set({ completions: c }),
  setJournalEntries: (j) => set({ journalEntries: j }), setDayNotes: (n) => set({ dayNotes: n }),
  setFocusSessions: (f) => set({ focusSessions: f }), setVacationPeriods: (v) => set({ vacationPeriods: v }),
  setTasks: (t) => set({ tasks: t }), setNotes: (n) => set({ notes: n }),
  setHomework: (h) => set({ homework: h }), setSubjects: (s) => set({ subjects: s }),
  showCreateModal: false, showCommandPalette: false, showFocusTimer: false, showDayNoteModal: false,
  editingHabit: null, searchQuery: '', selectedCategory: 'All',
  heatmapView: 'year', calendarMonth: new Date(),
  toasts: [],
  setShowCreateModal: (v) => set({ showCreateModal: v }),
  setShowCommandPalette: (v) => set({ showCommandPalette: v }),
  setShowFocusTimer: (v) => set({ showFocusTimer: v }),
  setShowDayNoteModal: (v) => set({ showDayNoteModal: v }),
  setEditingHabit: (h) => set({ editingHabit: h }),
  setSearchQuery: (q) => set({ searchQuery: q }), setSelectedCategory: (c) => set({ selectedCategory: c }),
  setHeatmapView: (v) => set({ heatmapView: v }), setCalendarMonth: (m) => set({ calendarMonth: m }),
  addToast: (t) => { const id=Date.now()+Math.random(); set(s=>({toasts:[...s.toasts,{...t,id}]})); setTimeout(()=>set(s=>({toasts:s.toasts.filter(x=>x.id!==id)})),3500); },
  quickCheckinMode: false, setQuickCheckinMode: (v) => set({ quickCheckinMode: v }),
  xp: 0, level: 1,
  addXp: (a) => { const nx=get().xp+a; const nl=Math.floor(nx/100)+1; const ol=get().level; set({xp:nx,level:nl}); if(nl>ol)get().addToast({type:'success',message:`Level up! Now level ${nl}`}); },
  achievements: [],
  unlockAchievement: (id) => { if(!get().achievements.includes(id)){set(s=>({achievements:[...s.achievements,id]}));get().addXp(50);get().addToast({type:'success',message:'Achievement unlocked! +50 XP'});}},
  focusTimerHabitId: null, setFocusTimerHabitId: (id) => set({ focusTimerHabitId: id }),
  selectedDate: null, setSelectedDate: (d) => set({ selectedDate: d }),
}));
