import React from 'react';
import {
  Zap, Flame, Target, Trophy, Star, Award, Crown, Shield, Medal, Rocket,
  Check, CheckCircle, X, Minus, Plus, Circle,
  ChevronLeft, ChevronRight, ChevronDown, ChevronUp,
  LayoutDashboard, BookOpen, BarChart3, Settings, HelpCircle, Search, Filter,
  Calendar, CalendarClock, Clock, Timer,
  ArrowLeft, Move, Activity,
  Dumbbell, Brain, Heart, HeartHandshake, Apple,
  Droplets, Moon, MoonStar, Sun, Wind, Footprints, Bike, Waves,
  StretchHorizontal, ShowerHead,
  BookMarked, Code, Lightbulb, GraduationCap, Languages,
  Palette, Paintbrush, Music, Camera, Headphones, PenLine,
  Users, Phone, Wallet, PiggyBank, HandHeart, MessageCircleHeart,
  Briefcase, Home, Focus, MonitorSmartphone, Smartphone, WifiOff,
  Sparkles, TreePine, Flower2, ChefHat, Coffee, Pill,
  Lock, Unlock, Eye, EyeOff, Download, Upload, HardDriveDownload,
  Trash2, Archive, Edit2, Save, Copy, Share2,
  Bell, BellOff, Volume2, VolumeX,
  Maximize2, Minimize2, Square,
  Menu, MoreHorizontal, MoreVertical,
  AlertCircle, AlertTriangle, Info, CheckSquare,
  Frown, Smile, Laugh,
  BatteryLow, Battery, BatteryMedium, BatteryFull,
  BedDouble,
  Sprout, Layers, Sword, Rainbow, Bird, PartyPopper,
  Quote, StickyNote,
  TrendingUp, TrendingDown, PieChart, LineChart,
  Gift, MapPin, Link, ExternalLink,
  RefreshCw, RotateCcw, Undo2, Redo2,
  GripVertical, ArrowUpDown,
  User, LogOut,
  FileText, FileJson, FolderOpen,
  Play, Pause, StopCircle,
  // New icons for v2 features
  Gauge, ShieldAlert, ListChecks, Wine, Ban,
  CloudRain, Palmtree, SkipForward,
  ShieldCheck, ShieldX, AlertOctagon,
  Hash, Type, List, ListOrdered,
} from 'lucide-react';

const iconMap = {
  Zap, Flame, Target, Trophy, Star, Award, Crown, Shield, Medal, Rocket,
  Check, CheckCircle, X, Minus, Plus, Circle,
  ChevronLeft, ChevronRight, ChevronDown, ChevronUp,
  LayoutDashboard, BookOpen, BarChart3, Settings, HelpCircle, Search, Filter,
  Calendar, CalendarClock, Clock, Timer,
  ArrowLeft, Move, Activity,
  Dumbbell, Brain, Heart, HeartHandshake, Apple,
  Droplets, Moon, MoonStar, Sun, Wind, Footprints, Bike, Waves,
  StretchHorizontal, ShowerHead,
  BookMarked, Code, Lightbulb, GraduationCap, Languages,
  Palette, Paintbrush, Music, Camera, Headphones, PenLine,
  Users, Phone, Wallet, PiggyBank, HandHeart, MessageCircleHeart,
  Briefcase, Home, Focus, MonitorSmartphone, Smartphone, WifiOff,
  Sparkles, TreePine, Flower2, ChefHat, Coffee, Pill,
  Lock, Unlock, Eye, EyeOff, Download, Upload, HardDriveDownload,
  Trash2, Archive, Edit2, Save, Copy, Share2,
  Bell, BellOff, Volume2, VolumeX,
  Maximize2, Minimize2, Square,
  Menu, MoreHorizontal, MoreVertical,
  AlertCircle, AlertTriangle, Info, CheckSquare,
  Frown, Smile, Laugh,
  BatteryLow, Battery, BatteryMedium, BatteryFull,
  BedDouble,
  Sprout, Layers, Sword, Rainbow, Bird, PartyPopper,
  Quote, StickyNote,
  TrendingUp, TrendingDown, PieChart, LineChart,
  Gift, MapPin, Link, ExternalLink,
  RefreshCw, RotateCcw, Undo2, Redo2,
  GripVertical, ArrowUpDown,
  User, LogOut,
  FileText, FileJson, FolderOpen,
  Play, Pause, StopCircle,
  Gauge, ShieldAlert, ListChecks, Wine, Ban,
  CloudRain, Palmtree, SkipForward,
  ShieldCheck, ShieldX, AlertOctagon,
  Hash, Type, List, ListOrdered,
  // Aliases
  SmartphoneOff: Smartphone,
  Run: Activity,
  Read: BookOpen,
  LightMode: Sun,
  DarkMode: Moon,
  ArrowForward: ChevronRight,
};

export default function DynIcon({ name, size = 16, color, strokeWidth = 2, style, className, ...rest }) {
  const IconComponent = iconMap[name];
  if (!IconComponent) {
    return <Zap size={size} color={color} strokeWidth={strokeWidth} style={style} className={className} {...rest} />;
  }
  return <IconComponent size={size} color={color} strokeWidth={strokeWidth} style={style} className={className} {...rest} />;
}
